name: build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows-x64-msvc
            os: windows-latest
            msvc_arch: x64
            cmd: BuildScripts\build_windows.bat x64

          - name: windows-x86-msvc
            os: windows-latest
            msvc_arch: x86
            cmd: BuildScripts\build_windows.bat x86

          - name: linux-x64-gcc
            os: ubuntu-latest
            cmd: bash BuildScripts/build_linux.sh

          - name: macos-arm64-appleclang
            os: macos-latest
            cmd: bash BuildScripts/build_macos.sh arm64

          - name: macos-x64-appleclang
            os: macos-latest
            cmd: bash BuildScripts/build_macos.sh x86_64

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      - name: chmod BuildScripts
        if: runner.os != 'Windows'
        run: chmod +x BuildScripts/*.sh

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: ${{ matrix.cmd }}

      - name: Build
        if: runner.os != 'Windows'
        shell: bash
        run: ${{ matrix.cmd }}
